---
# tasks file for k3s-workers

- name: get node token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: node_token_result
  become: yes
  delegate_to: "{{ groups['k3s_masters'][0] }}"

- set_fact:
    node_token: "{{ node_token_result.stdout }}"
    master_ip: "{{ hostvars[groups['k3s_masters'][0]].internal_ip }}"

- name: create Downloads directory
  file:
    path: Downloads
    state: directory
    mode: '0755'

- name: get k3s installer
  get_url:
    url: https://get.k3s.io
    dest: "{{ ansible_user_dir }}/Downloads/k3s-setup.sh"
    mode: '0644'
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: use_proxy

- name: get k3s installer
  get_url:
    url: https://get.k3s.io
    dest: "{{ ansible_user_dir }}/Downloads/k3s-setup.sh"
    mode: '0644'
  when: not use_proxy

- name: install k3s no proxy
  shell: >
    cat Downloads/k3s-setup.sh | 
    INSTALL_K3S_VERSION="{{ k3s_version }}" 
    INSTALL_K3S_EXEC="--node-ip {{ internal_ip }} --node-external-ip {{ external_ip }}" 
    K3S_URL="https://{{ master_ip }}:6443" 
    K3S_TOKEN="{{ node_token }}" 
    sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  when: not use_proxy
  register: workers_install_result
  become: yes

- name: results of installation
  debug: var=workers_install_result
  when: workers_install_result is changed

- name: install k3s with proxy
  shell: >
    cat Downloads/k3s-setup.sh | 
    INSTALL_K3S_VERSION="{{ k3s_version }}" 
    INSTALL_K3S_EXEC="--node-ip {{ internal_ip }} --node-external-ip {{ external_ip }}" 
    K3S_URL="https://{{ master_ip }}:6443" 
    K3S_TOKEN="{{ node_token }}" 
    HTTP_PROXY="{{ proxy }}" 
    HTTPS_PROXY="{{ proxy }}" 
    NO_PROXY="{{ no_proxy }}" 
    sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  when: use_proxy
  register: workers_install_result
  become: yes

- name: results of installation
  debug: var=workers_install_result
  when: workers_install_result is changed
